export const MAGIC_EDEN_DOMAINS = ["magiceden.io", "www.magiceden.io"];

export const MESSAGE_REQUEST_COLLECTION_INFO =
  "MESSAGE_REQUEST_COLLECTION_INFO";

export const MESSAGE_SET_LISTING_NOTIFICATIONS =
  "MESSAGE_SET_LISTING_NOTIFICATIONS";

export const MESSAGE_SET_FP_NOTIFICATIONS = "MESSAGE_SET_FP_NOTIFICATIONS";

export const MESSAGE_SET_REFRESH_INTERVAL = "MESSAGE_SET_REFRESH_INTERVAL";

export const MESSAGE_GET_REFRESH_INTERVAL = "MESSAGE_GET_REFRESH_INTERVAL";

export const MESSAGE_URL_UPDATED = "MESSAGE_URL_UPDATED";

export const ALARM_NAME = "ME_SNIPER";

export const PARROT_TITLE = "PARROT";

export const SOL_MAGIC_NUMBER = 1000000000;

export const MAGIC_EDEN_DOMAIN = "https://magiceden.io";
